# Generated by Django 5.2.1 on 2025-05-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcoupon",
            name="dislikes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productcoupon",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productcoupon",
            name="used_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productcoupon",
            name="used_today",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
