# Generated by Django 5.2.1 on 2025-05-18 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_productcoupon_expiry_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcoupon",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="productcoupon",
            name="likes",
        ),
    ]
