# Generated by Django 5.2.1 on 2025-05-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_productcoupon_dislikes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="product_logos/"),
        ),
        migrations.AddField(
            model_name="product",
            name="logo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="sub_subtitle",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
