# Generated by Django 5.2.1 on 2025-05-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0005_product_logo_product_logo_url_product_sub_subtitle_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcoupon",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
