# Generated by Django 5.2.1 on 2025-05-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_approved_product_footer_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='social_facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='social_instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='social_twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
