# Generated by Django 5.2.1 on 2025-05-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_social_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='footer_section_how_to_use_steps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='footer_section_tips_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
