# Generated by Django 5.2.1 on 2025-05-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_footer_section_how_to_use_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcoupon',
            name='shop_now_url',
            field=models.URLField(blank=True, null=True, verbose_name='Shop Now Link'),
        ),
    ]
