# Generated by Django 5.2.1 on 2025-05-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productcoupon_shop_now_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcoupon',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
