# Generated by Django 5.2.1 on 2025-05-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productcoupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcoupon',
            name='discount',
            field=models.CharField(max_length=50),
        ),
    ]
