# Generated by Django 5.2.1 on 2025-05-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_productcoupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_affiliate_url',
            field=models.URLField(blank=True, help_text='Primary affiliate link for the product (e.g., used on logo, social buttons)', null=True, verbose_name='Main Product Affiliate Link'),
        ),
    ]
