# Generated by Django 5.2.1 on 2025-05-31 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
