# Generated by Django 5.2.1 on 2025-06-01 15:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcoupon',
            name='last_reset_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
