# Generated by Django 5.2.1 on 2025-06-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productcoupon_last_reset_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcoupon',
            name='last_reset_date',
        ),
        migrations.AddField(
            model_name='product',
            name='is_signup_store',
            field=models.BooleanField(default=False, help_text="Check this box if the primary call to action for this store/product should be 'Sign Up' instead of 'Shop Now'."),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
