# Generated by Django 5.2.1 on 2025-06-07 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_productcoupon_last_reset_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcoupon',
            name='last_reset_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
